apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: control
  namespace: travel-control
spec:
  host: control.travel-control.svc.cluster.local
  subsets:
    - labels:
        version: {{ .Values.appVersion }}
      name: v1
