apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: control
  namespace: travel-control
spec:
  hosts:
    - istio-ingressgateway-istio-system.{{ .Values.global.localClusterDomain }}
  gateways:
    - istio-system/control-gateway
  http:
    - route:
        - destination:
            host: control.travel-control.svc.cluster.local
            subset: v1
          weight: 100
