{{- with $jaeger := .Values.jaeger }}
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-{{ $.Values.global.jaeger.strategy }}
spec:
  strategy: {{ $.Values.global.jaeger.strategy }}
  storage:
    type: {{ $jaeger.storage | lower }}
{{- end }}
{{- with .Values.elasticsearch }}
{{- $index := .indexCleaner }}
    esIndexCleaner:
      enabled: {{ $index.enabled }}
      numberOfDays: {{ $index.days }}
      schedule: {{ $index.schedule | squote }}
{{- end }}
{{- with $es := .Values.elasticsearch }}
    elasticsearch:
      nodeCount: {{ $es.nodeCount }}
      storage:
        size: {{ $es.storage.size }}
      resources:
        requests:
          cpu: {{ $es.requests.cpu }}
          memory: {{ $es.requests.memory }}
        limits:
          memory: {{ $es.requests.memory }}
      redundancyPolicy: {{ $es.redundancyPolicy }}
{{- end }}
