apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: production
spec:
  security:
    dataPlane:
      automtls: {{ default true .Values.security.dataPlane.automtls }}
      mtls: {{ default true .Values.security.dataPlane.mtls }}
{{- with $trace := .Values.jaeger.tracing }}
  tracing:
    sampling: {{ default 10000 $trace.sampling }}
    type: {{ default "Jaeger" $trace.type }}
{{- end }}
  general:
    logging:
      logAsJSON: true
  profiles:
    - {{ .Values.smcp.profiles }}
  proxy:
    resources:
      requests:
        cpu: {{ .Values.proxy.requests.cpu }}
        memory: {{ .Values.proxy.requests.memory }}
      limits:
        cpu: {{ .Values.proxy.limits.cpu }}
        memory: {{ .Values.proxy.limits.memory }}
    accessLogging:
      file:
        name: /dev/stdout
    networking:
      trafficControl:
        inbound: {}
        outbound:
          policy: REGISTRY_ONLY
{{- include "servicemesh.gateways" . | indent 2 }}
  policy:
    type: Istiod
  addons:
{{- include "servicemesh.addons" . | indent 4 }}
  runtime:
{{- include "servicemesh.runtime" . | indent 4 }}
  version: {{ .Values.smcp.version }}
  telemetry:
    type: Istiod
