apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: {{ .Values.controlPlane.deploymentStrategy }}
spec:
  security:
    dataPlane:
{{- if eq .Values.controlPlane.deploymentStrategy "production" }}
      automtls: true
      mtls: true
{{- else }}
      automtls: {{ default true .Values.security.dataPlane.automls }}
      mtls: {{ default true .Values.security.dataPlane.mtls }}
{{- end }}
{{- with $trace := .Values.jaeger.tracing }}
  tracing:
    sampling: {{ default 10000 $trace.sampling }}
    type: {{ default "Jaeger" $trace.type }}
{{- end }}
  general:
    logging:
      logAsJSON: true
  profiles:
    - {{ .Values.controlPlane.profiles }}
  proxy:
    accessLogging:
      file:
        name: /dev/stdout
    networking:
      trafficControl:
        inbound: {}
        outbound:
          policy: REGISTRY_ONLY
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      name: {{ .Values.jaeger.name }}-{{ .Values.controlPlane.deploymentStrategy }}
      install:
    {{- if eq .Values.controlPlane.deploymentStrategy "production" }}
        ingress:
          enabled: true
        storage:
          type: {{ .Values.jaeger.storage }}
    {{- else }}
        storage:
          type: Memory
    {{- end }}
    kiali:
      enabled: true
    prometheus:
      enabled: true
  version: {{ .Values.controlPlane.version }}
  telemetry:
    type: Istiod
