apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: travelops-agency-role
  namespace: travel-agency
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
  - patch
