apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: travelops-agency-rolebinding
  namespace: travel-agency
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: travelops-agency-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: travel-agency
