# Default values for controlplane.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# START of Global Value declaration
global:
  localClusterDomain: ''

# END of Global Values

# Configure servicemesh controlplane version and profile to use
smcp:
  version: v2.6
  profiles: default
  mode: ClusterWide
  tracing:
    type: ''
    sampling: 10000

# Define the namespaces that belong in the service mesh
# Use this when defining memberRoll outside of demo applications
mesh:
  members: {}

# Enable or disable mtls and automtls. BOTH ARE DEFAULT ENABLED
security:
  dataPlane:
    automtls: ''
    mtls: ''

# Configure proxy resources requests and limits
proxy:
 requests:
   cpu: 100m
   memory: 128Mi
 limits:
   cpu: 500m
   memory: 128Mi

# Configure ingress/egress gateways 
gateways:
  enabled: true
  egress:
    enabled: true
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 2
  ingress:
    enabled: true
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 2
# Istio OpenShift Routing (IOR) (automatic route creation) is disabled by default in lieu of explicitly defined ingress 
# See the docs: https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html-single/service_mesh/index#ossm-route-migration
  openshiftRoute:
    enabled: false

# Configure Grafana addon resources
grafana:
  enabled: true
  persistence:
    enabled: true
    storageClassName: ""
    accessMode: ReadWriteOnce
    capacity:
      requests:
        storage: 5Gi
  service:
    ingress:
      contextPath: /grafana
      tls:
        termination: reencrypt
      
# Define runtime resources
pilot:
  deployment:
    replicas: 2
