apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: control-gateway
  namespace: 
spec:
  servers:
    - hosts:
        - istio-ingressgateway-{{ .Values.appEnv }}-istio-system.{{ .Values.global.localDomain }}
      port:
        name: http
        number: 80
        protocol: HTTP
  selector:
    istio: ingressgateway