apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: control-gateway
  namespace: istio-system
  annotations:
    maistra.io/manageRoute: 'false'
    argocd.argoproj.io/sync-options: Validate=false, SkipDryRunOnMissingResource=true
spec:
  servers:
    - hosts:
        - istio-ingressgateway-istio-system.{{ .Values.global.localClusterDomain }}
      port:
        name: http
        number: 80
        protocol: HTTP
  selector:
    istio: ingressgateway
