apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ca
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-options: Validate=false, SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "6"
spec:
  isCA: true
  duration: "21600h0m0s"
  secretName: istio-ca
  commonName: istio-ca.my-company.net
  subject:
    organizations:
    - my-company.net
  issuerRef:
    name: root-ca
    kind: ClusterIssuer
    group: cert-manager.io
