---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: istio-ca
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true, Validate=false, SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
spec:
  ca:
    secretName: istio-ca
