apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: root-ca
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true, Validate=false, SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
spec:
  ca:
    secretName: root-ca
