apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: travelops-control-rolebinding
  namespace: travel-control
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: travelops-control-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: travel-control
