apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: control
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true, Validate=false
    argocd.argoproj.io/sync-wave: "8"
spec:
  hosts:
    - istio-ingressgateway-istio-system.{{ .Values.global.localClusterDomain }}
  gateways:
    - istio-system/control-gateway
  http:
    - route:
        - destination:
            host: control.travel-control.svc.cluster.local
            subset: v1
          weight: 100
