---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: htpass-eso
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: htpasswd
  dataFrom:
  - extract:
      key: {{ .Values.htpasswd.key }}
